### ISSUE TITLE
Add missing card images

### ISSUE THREAD

**Issue by micolous** [micolous/metrodroid#199]
## Description of the issue

Missing card images added in other pull requests:

- [ ] Ventra (Chicago, IL, USA)
- [x] Trimet (Portland, OR, USA)
- [ ] Viva (Lisboa, Portugal)
- [ ] Envibus (France)
- [ ] Navigo (France)
- [ ] OùRA (France)
- [ ] TaM (France)
- [ ] Transgironde (France)
- [x] Mobib (Belgium)
- [ ] RicaricaMi (Italy)
- [ ] Adelaide Metro
- [ ] Beijing
- [ ] City Union
- [ ] Pastel (France)
- [ ] Kiev
- [ ] MetroQ (Houston)
- [ ] Selecta (France)
- [ ] SunCard (Orlando)
- [ ] Tartu Bus
- [ ] Wuhan Tong

**Comment by phcoder** [comment]
All of this except CityUnion either have been added or in Pull requests queue.
In all currently missing are: City Union, Magna Carta and Intercard

**Comment by phcoder** [comment]
CityUnion is in PR as well

**Comment by phcoder** [comment]
MagnaCarta and Intercard as well (it's logos and not individual cards)

**Comment by phcoder** [comment]
This can be closed
