### ISSUE TITLE
TAP Card Expiration Date

### ISSUE THREAD

**Issue by steets250** [micolous/metrodroid#24]
Hi Micolous,

The TAP Card functionality on the app is wonderful. I'm working on compiling a list of bus routes and the remaining train stops to add eventually.

In the mean time, I believe I've found the sector of the card that shows when the card expires. 
[card_data.txt](https://github.com/micolous/metrodroid/files/671671/card_data.txt)

Would it be possible to add in the expiration data as part of the card's information page in the app?

Thanks, Steven

**Comment by micolous** [comment]
Looks like this is just storing the date, so should be straight forward to extract.  I think you have the right sector.
