### ISSUE TITLE
Setup LAX TAP support for Stops website

### ISSUE THREAD

**Issue by micolous** [micolous/metrodroid#25]
At present, Stops website only supports the Go card.  It should also support LAX TAP card.

There are some quirks to handle:

- Multiple agencies, not just 1 agency.
- Metro Bus stop IDs actually show the route number, not the stop at which the service was boarded

This will need some refactoring of the site.

**Comment by phcoder** [comment]
Given that stops has been turned down, I think this can be closed

**Comment by micolous** [comment]
Agreed!
