### ISSUE TITLE
Clipper single-use tickets throw TagLostException in v2.9.38

### ISSUE THREAD

**Issue by iangcarroll** [micolous/metrodroid#383]
Please read the guidelines for contributions (CONTRIBUTING.md) before submitting new issues to this tracker. Failure to adhere to these guidelines may cause offense.

## Description of the issue
Clipper single-use tickets fail to read in v2.9.38, throwing a TagLostException on my Pixel 3. I'm doing some research on these and have plenty of dumps if needed.

## For card-specific issues

- Name of the card type: Clipper (single-use)
- Name of the transit operator: Clipper
- Location: San Francisco, CA

For all issues reading a _currently supported card format_ (eg: balance shown is incorrect), please export a card dump from Metrodroid and email it to me privately.

## Steps to reproduce

1. Scan a Clipper single-use ticket (only tested with Muni-issued ones).
2. 
3. 

## Expected behaviour
Card reads, as it does in v2.9.37.

## Actual behaviour
TagLostException every time.

## Logs

Generate a bug report ZIP using the instructions here: https://developer.android.com/studio/debug/bug-report.html

Please do not attach it to this issue. You may be asked for a copy later via private email.

## Details from About screen:

- Version: 
- Model: Pixel 3 (blueline)
- Manufacturer: Google (google)
- Android OS version: 9 (PQ2A.190405.003)
- NFC: enabled
- MIFARE Classic: not supported

**Comment by phcoder** [comment]
Try https://github.com/micolous/metrodroid/pull/384

**Comment by micolous** [comment]
This will be fixed in v2.9.40.
